<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <PlatformTarget>x64</PlatformTarget>
    <OutputPath>../Assemblies</OutputPath>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Assembly-CSharp">
      <HintPath>D:\Program Files (x86)\Steam\steamapps\common\RimWorld\RimWorldWin64_Data\Managed\Assembly-CSharp.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Verse">
      <HintPath>D:\Program Files (x86)\Steam\steamapps\common\RimWorld\Mods\Core\Assemblies\Verse.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="RimWorld">
      <HintPath>D:\Program Files (x86)\Steam\steamapps\common\RimWorld\Mods\Core\Assemblies\RimWorld.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>D:\Program Files (x86)\Steam\steamapps\common\RimWorld\RimWorldWin64_Data\Managed\UnityEngine.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>D:\Program Files (x86)\Steam\steamapps\common\RimWorld\RimWorldWin64_Data\Managed\UnityEngine.CoreModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="MagicFramework">
      <HintPath>../../MagicFramework/Assemblies/MagicFramework.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>

</Project>
